###
GET http://localhost:3000/filmes

###
POST http://localhost:3000/filmes
Content-Type: application/json

{
 "titulo": "Pixels",
 "genero": "Jogos",
 "ano_lancamento": "2015",
 "diretor": "Chris Columbus"
}
###
PUT http://localhost:3000/filmes/2
Content-Type: application/json

{
  "titulo": "Gremleeeeins",
 "genero": "Comédia",
 "ano_lancamento": "1984",
 "diretor": "Joe Dante"
}
###
DELETE http://localhost:3000/filmes/1