###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Guilherme",
    "senha": "12345",
    "email": "guilherme1228@estudante.com"
}

###

PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome": "Carlos",
    "email": "guilherme18@estudante.com",
    "senha": "12345"
}

###

DELETE http://localhost:3000/usuarios/2

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "guilherme18@estudante.com",
    "senha": "12345"
}